org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.234
neo_version_range=[21.1.234,21.2)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
java_version=21

mod_id=the_coinage
mod_name=The Coinage
mod_license=MPL-2.0
mod_version=1.0.2
mod_group_id=io.github.tracerxbrhd
mod_authors=tracerxbrhd
mod_description=Ancient physical copper, silver and gold currency with a smart Coin Purse, world loot, trades and a stable mod integration API.

u_api_version=2.1.2
u_api_version_range=[2.1.0,3.0.0)
release_remote=github
