org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.28-beta
neo_version_range=[26.2.0.28-beta,)
loader_version_range=[4,)
java_version=25

mod_id=the_coinage
mod_name=The Coinage
mod_license=MPL-2.0
mod_version=1.0.2
mod_group_id=io.github.tracerxbrhd
mod_authors=tracerxbrhd
mod_description=Ancient physical copper, silver and gold currency with a smart Coin Purse, world loot, trades and a stable mod integration API.

u_api_version=3.0.0
u_api_version_range=[3.0.0,4.0.0)
u_api_local_path=../u-api-26.2
release_remote=github
